# Generated by Django 3.2.3 on 2021-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=150, verbose_name='Ad və soyad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Kommentsayı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150, verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='Article.Subcategory', verbose_name='Subkateqoriya'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.CharField(max_length=150, verbose_name='Subkateqoriya'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users', to='Article.user', verbose_name='Yazar'),
        ),
    ]
